package NewsArticles;

import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

import DarylUI.Masterpanel;

public class World3 extends Masterpanel {

	/**
	 * Create the panel.
	 */
	public World3(JFrame mf) throws IOException, FontFormatException {
		super(mf);
		
		JTextArea Info = new JTextArea();
		Info.setEditable(false);
		Info.setWrapStyleWord(true);
		Info.setLineWrap(true);
		Info.setText("North Korea said it carried out the test on Wednesday - if confirmed it would be its fourth nuclear test, and its first of the more powerful hydrogen bomb.\r\n\r\nThe UN Security Council has also agreed to start drawing up new measures against North Korea.\r\nBut scepticism remains over whether the North really did conduct such a test.\r\n\r\nExperts have said the seismic activity generated by the blast was not large enough for it to have been a full thermonuclear explosion.\r\n\r\nThe White House said President Barack Obama had spoken separately to South Korea's President Park Geun-Hye and Japan's Prime Minister Shinzo Abe.\r\n\r\nThey \"agreed to work together to forge a united and strong international response to North Korea's latest reckless behaviour\", it said in a statement.\r\n");
		Info.setBounds(15, 116, 570, 318);
		JScrollPane scrollPane = new JScrollPane(Info);
		scrollPane.setBounds(15, 116, 570, 318);
		add(scrollPane);
		
		JLabel Headline = new JLabel("N Korea nuclear: US, Japan, S Korea pledge united response\r\n");
		Headline.setFont(new Font("Malgun Gothic", Font.PLAIN, 24));
		Headline.setBounds(15, 40, 509, 33);
		add(Headline);
		File font_file = new File("Fonts/RobotoCondensed-Regular.ttf");
		Font font = Font.createFont(Font.TRUETYPE_FONT, font_file);
		Font sizedFont = font.deriveFont(20f);
		File font2_file = new File("Fonts/RobotoCondensed-Bold.ttf");
		Font font2 = Font.createFont(Font.TRUETYPE_FONT, font2_file);
		Font headlineFont = font2.deriveFont(20f);
		Info.setFont(sizedFont);
		Headline.setFont(headlineFont);
	}

}
